server:
  port: 9090

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/FaceEmreAuthDB
    username: postgres
    password: 1234bilgeADAM
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true
    properties:
      hibernate:
        format_sql: true

my-application:
  jwt:
    secret-key-env: ${SECRETKEYJWT}